'use strict';
// Native Electron integration check; invoked by the isolated desktop harness.
const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
module.exports=async(window,root,{calls,setMissingJava})=>{
  const js=code=>window.webContents.executeJavaScript(code);
  const until=async predicate=>{const limit=Date.now()+30000;while(!await js(predicate)){if(Date.now()>limit)throw new Error('Java UI timeout: '+predicate);await new Promise(resolve=>setTimeout(resolve,80));}};
  const choose=async language=>{await js(`document.getElementById('coding-language').value=${JSON.stringify(language)};document.getElementById('coding-language').dispatchEvent(new Event('change'));`);await until(`!document.getElementById('coding-language').disabled && document.getElementById('coding-language').value===${JSON.stringify(language)} && document.getElementById('coding-save-state').textContent!=='正在保存…'`);};
  const action=async(button,expected)=>{await js(`document.getElementById('coding-result').textContent='';document.getElementById(${JSON.stringify(button)}).click()`);await until(`document.getElementById('coding-stop').hidden && document.getElementById('coding-result').textContent.includes(${JSON.stringify(expected)})`);};
  const cpp=await js('window.LeetCoding.editors.core.get()');
  await choose('java');
  await js('window.LeetCoding.ensureCompiler(true)');
  await js(`if(!document.getElementById('core-editor').getAttribute('aria-label').includes('Java'))throw new Error('Java editor not selected')`);
  const core='class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        Map<Integer, Integer> seen = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            Integer other = seen.get(target - nums[i]);\n            if (other != null) return new int[]{other, i};\n            seen.put(nums[i], i);\n        }\n        return new int[0];\n    }\n}\n';
  await js(`window.LeetCoding.editors.core.replace(${JSON.stringify(core)});document.querySelector('[data-mode="acm"]').click()`);
  await until(`!document.getElementById('coding-check').disabled`);
  await action('coding-check','输入解析和输出格式通过');
  await action('coding-run','本地运行结束');
  await js(`if(!document.getElementById('coding-result').textContent.includes('0 1'))throw new Error('Java local sample result missing')`);
  const main=await js('window.LeetCoding.editors.main.get()');
  await js(`window.LeetCoding.editors.main.replace(${JSON.stringify(main.replace('twoSum(nums, target)','twoSum(nums, target + 1)'))})`);
  await action('coding-check','输入输出检查未通过');
  await js(`if(!document.getElementById('coding-input-status').classList.contains('failed')||!document.getElementById('coding-output-status').classList.contains('passed'))throw new Error('Java argument mismatch not isolated')`);
  await js(`window.LeetCoding.editors.main.replace(${JSON.stringify(main)})`);
  await action('coding-submit','力扣提交 · Accepted');
  const submit=calls.filter(call=>call.route.endsWith('/submit/')).at(-1),payload=JSON.parse(submit.opts.body);
  assert.equal(payload.lang,'java');assert.equal(payload.typed_code,core);assert.equal('main' in payload,false);
  await choose('cpp');assert.equal(await js('window.LeetCoding.editors.core.get()'),cpp);
  await choose('java');assert.equal(await js('window.LeetCoding.editors.core.get()'),core);assert.equal(await js('window.LeetCoding.editors.main.get()'),main);
  setMissingJava(true);await js('window.LeetCoding.ensureCompiler(true)');
  await js(`if(!document.getElementById('coding-run').disabled||!document.getElementById('coding-submit').disabled)throw new Error('Missing JDK must disable local actions');document.querySelector('[data-mode="leetcode"]').click();if(document.getElementById('coding-run').disabled)throw new Error('LeetCode mode must work without JDK')`);
  await action('coding-run','力扣运行 · Accepted');
  await choose('cpp');await js(`document.querySelector('[data-mode="acm"]').click();if(document.getElementById('coding-run').disabled)throw new Error('Missing Java blocked C++')`);
  setMissingJava(false);await choose('java');await js('window.LeetCoding.ensureCompiler(true)');
  await js('window.LeetCoding.flush()');
  await window.loadFile(path.join(root,'src','index.html'));
  await until(`document.getElementById('account-label').textContent==='示例账号'`);
  await js(`document.querySelector('[data-view="coding"]').click()`);
  await until(`document.getElementById('coding-title').textContent==='两数之和' && !document.getElementById('coding-language').disabled && !document.getElementById('coding-run').disabled`);
  assert.equal(await js(`document.getElementById('coding-language').value`),'java');
  assert.equal(await js('window.LeetCoding.editors.core.get()'),core);
  await js(`document.getElementById('settings-open').click()`);
  await until(`document.getElementById('coding-java-compiler-state').textContent.includes('javac')`);
  await js(`document.getElementById('settings-close').click();document.querySelector('[data-mode="acm"]').click()`);
  window.setSize(980,680);
  await js('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
  await js(`(()=>{const desk=document.querySelector('.coding-desk').getBoundingClientRect(),language=document.getElementById('coding-language').getBoundingClientRect();if(document.documentElement.scrollWidth>innerWidth||desk.bottom>innerHeight||language.width===0||language.height===0||language.right>innerWidth)throw new Error('Java compact layout or language selector unavailable');})()`);
  await choose('cpp');assert.equal(await js('window.LeetCoding.editors.core.get()'),cpp);
  await choose('java');assert.equal(await js('window.LeetCoding.editors.core.get()'),core);
  const dir=path.join(root,'artifacts','java-desktop');await fs.mkdir(dir,{recursive:true});
  await fs.writeFile(path.join(dir,'java-compact.png'),(await window.webContents.capturePage()).toPNG());
  await fs.writeFile(path.join(dir,'ui-check.json'),JSON.stringify({languages:['cpp','java'],realJavaCompile:true,ioErrors:true,separateDrafts:true,restoreAfterReload:true,missingJdkHandling:true,compactFits:true,remoteVerdicts:'isolated fixtures only'},null,2));
  console.log('JAVA_UI_CHECK_OK');
};
